<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FondalandIVLauncher</AssemblyName>
    <RootNamespace>FondalandIVLauncher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\fondaland-background.jpg" />
  </ItemGroup>
</Project>
